# Generated by Django 5.2.1 on 2025-05-19 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0002_order_offer_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='business_user_id',
            new_name='business_user',
        ),
    ]
