# Generated by Django 5.2.1 on 2025-05-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0003_rename_business_user_id_order_business_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_id',
        ),
    ]
