# Generated by Django 5.2.1 on 2025-05-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0009_alter_order_business_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='business_user',
            field=models.IntegerField(),
        ),
    ]
