# Generated by Django 5.2.1 on 2025-05-15 11:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='price',
            new_name='min_price',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='is_active',
        ),
        migrations.AddField(
            model_name='offer',
            name='min_delivery_time',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
