# Generated by Django 5.2.1 on 2025-05-16 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_rename_price_offer_min_price_remove_offer_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='min_delivery_time',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='offerdetail',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='offerdetail',
            name='shipping_info',
        ),
        migrations.RemoveField(
            model_name='offerdetail',
            name='warranty_period_months',
        ),
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offer_images/'),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='delivery_time_in_days',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='features',
            field=models.JSONField(default=['test', 'tesT']),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='offer_type',
            field=models.CharField(default='basic', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='revisions',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='title',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='offers_app.offer'),
        ),
    ]
