# Generated by Django 5.2.1 on 2025-05-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0005_offer_user_alter_offer_image_alter_offer_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='revisions',
            field=models.IntegerField(),
        ),
    ]
