# Generated by Django 5.2.1 on 2025-05-21 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0006_alter_offerdetail_revisions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt, zu dem das Angebot erstellt wurde.'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(help_text='Ausführliche Beschreibung des Angebots.'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, help_text='Optionales Bild zum Angebot.', null=True, upload_to='offers/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(help_text='Titel des Angebots.', max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aktualisierung des Angebots.'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='user',
            field=models.ForeignKey(help_text='Der Benutzer, der dieses Angebot erstellt hat.', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='delivery_time_in_days',
            field=models.PositiveIntegerField(help_text='Lieferzeit in Tagen für diese Variante.'),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='features',
            field=models.JSONField(default=list, help_text='Liste der besonderen Merkmale oder Features des Angebots.'),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='offer',
            field=models.ForeignKey(help_text='Das zugehörige Angebot, zu dem dieses Detail gehört.', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='offers_app.offer'),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='offer_type',
            field=models.CharField(help_text='Typ des Angebots (z.B. Basic, Premium, etc.).', max_length=20),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Preis der Angebotsvariante.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='revisions',
            field=models.IntegerField(help_text='Anzahl der erlaubten Überarbeitungen/Revisionsrunden.'),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='title',
            field=models.CharField(help_text='Titel oder Name der Angebotsvariante.', max_length=255),
        ),
    ]
