# Generated by Django 5.2.1 on 2025-05-15 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
