# Generated by Django 5.2.1 on 2025-05-20 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_remove_userprofile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_number',
            new_name='tel',
        ),
    ]
