# Generated by Django 5.2.1 on 2025-05-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_userprofile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='working_hours',
            field=models.TextField(blank=True, null=True),
        ),
    ]
