# Generated by Django 5.2.1 on 2025-05-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_userprofile_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
