# Generated by Django 5.2.1 on 2025-05-21 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_userprofile_address_userprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
    ]
