# Generated by Django 5.2.1 on 2025-05-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_alter_userprofile_description_alter_userprofile_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='file',
            field=models.ImageField(blank=True, default='profile_pic.svg', upload_to='profiles/'),
        ),
    ]
