# Generated by Django 5.2.1 on 2025-05-21 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0002_rename_comment_review_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='business_user',
            field=models.ForeignKey(help_text='Der Nutzer, der die Bewertung erhält.', on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung der Bewertung.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(help_text='Freitextliche Beschreibung zur Bewertung.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(help_text='Bewertungswert als ganze Zahl (z.B. 1-5 Sterne).'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(help_text='Der Nutzer, der die Bewertung schreibt.', on_delete=django.db.models.deletion.CASCADE, related_name='written_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aktualisierung der Bewertung.'),
        ),
    ]
